/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nawal' at '8/11/16 12:58 PM' with Gradle 3.1
 *
 * @author nawal, @date 8/11/16 12:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
