import org.junit.Test;
import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'nawal' at '8/11/16 12:58 PM' with Gradle 3.1
 *
 * @author nawal, @date 8/11/16 12:58 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
